// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import mirnator.sql2java.exception.DAOException;

/**
 * Listener that is notified of kgsequence table changes.
 * @author sql2java
 */
public interface KgsequenceListener
{
    /**
     * Invoked just before inserting a KgsequenceBean record into the database.
     *
     * @param bean the KgsequenceBean that is about to be inserted
     */
    public void beforeInsert(KgsequenceBean bean) throws DAOException;


    /**
     * Invoked just after a KgsequenceBean record is inserted in the database.
     *
     * @param bean the KgsequenceBean that was just inserted
     */
    public void afterInsert(KgsequenceBean bean) throws DAOException;


    /**
     * Invoked just before updating a KgsequenceBean record in the database.
     *
     * @param bean the KgsequenceBean that is about to be updated
     */
    public void beforeUpdate(KgsequenceBean bean) throws DAOException;


    /**
     * Invoked just after updating a KgsequenceBean record in the database.
     *
     * @param bean the KgsequenceBean that was just updated
     */
    public void afterUpdate(KgsequenceBean bean) throws DAOException;


    /**
     * Invoked just before deleting a KgsequenceBean record in the database.
     *
     * @param bean the KgsequenceBean that is about to be deleted
     */
    public void beforeDelete(KgsequenceBean bean) throws DAOException;


    /**
     * Invoked just after deleting a KgsequenceBean record in the database.
     *
     * @param bean the KgsequenceBean that was just deleted
     */
    public void afterDelete(KgsequenceBean bean) throws DAOException;

}
