// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import java.util.Comparator;


/**
 * Comparator class is used to sort the KgsequenceBean objects.
 * @author sql2java
 */
@SuppressWarnings("rawtypes")
public class KgsequenceComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for KgsequenceComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new KgsequenceComparator(KgsequenceManager.ID_MRNA_SEQUENCE, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>KgsequenceManager.ID_MRNA_SEQUENCE
     *   <li>KgsequenceManager.ID_KNOWNGENE_REF
     *   <li>KgsequenceManager.ID_SEQUENCE_ID
     * </ul>
     */
    public KgsequenceComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for KgsequenceComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new KgsequenceComparator(KgsequenceManager.ID_MRNA_SEQUENCE, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>KgsequenceManager.ID_MRNA_SEQUENCE
     *   <li>KgsequenceManager.ID_KNOWNGENE_REF
     *   <li>KgsequenceManager.ID_SEQUENCE_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public KgsequenceComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        KgsequenceBean b1 = (KgsequenceBean)pObj1;
        KgsequenceBean b2 = (KgsequenceBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case KgsequenceManager.ID_MRNA_SEQUENCE:
                if (b1.getMrnaSequence() == null && b2.getMrnaSequence() != null) {
                    iReturn = -1;
                } else if (b1.getMrnaSequence() == null && b2.getMrnaSequence() == null) {
                    iReturn = 0;
                } else if (b1.getMrnaSequence() != null && b2.getMrnaSequence() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getMrnaSequence().compareTo(b2.getMrnaSequence());
                }
                break;
            case KgsequenceManager.ID_KNOWNGENE_REF:
                if (b1.getKnowngeneRef() == null && b2.getKnowngeneRef() != null) {
                    iReturn = -1;
                } else if (b1.getKnowngeneRef() == null && b2.getKnowngeneRef() == null) {
                    iReturn = 0;
                } else if (b1.getKnowngeneRef() != null && b2.getKnowngeneRef() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getKnowngeneRef().compareTo(b2.getKnowngeneRef());
                }
                break;
            case KgsequenceManager.ID_SEQUENCE_ID:
                if (b1.getSequenceId() == null && b2.getSequenceId() != null) {
                    iReturn = -1;
                } else if (b1.getSequenceId() == null && b2.getSequenceId() == null) {
                    iReturn = 0;
                } else if (b1.getSequenceId() != null && b2.getSequenceId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getSequenceId().compareTo(b2.getSequenceId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
