// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import mirnator.sql2java.exception.DAOException;

/**
 * Listener that is notified of knowngene table changes.
 * @author sql2java
 */
public interface KnowngeneListener
{
    /**
     * Invoked just before inserting a KnowngeneBean record into the database.
     *
     * @param bean the KnowngeneBean that is about to be inserted
     */
    public void beforeInsert(KnowngeneBean bean) throws DAOException;


    /**
     * Invoked just after a KnowngeneBean record is inserted in the database.
     *
     * @param bean the KnowngeneBean that was just inserted
     */
    public void afterInsert(KnowngeneBean bean) throws DAOException;


    /**
     * Invoked just before updating a KnowngeneBean record in the database.
     *
     * @param bean the KnowngeneBean that is about to be updated
     */
    public void beforeUpdate(KnowngeneBean bean) throws DAOException;


    /**
     * Invoked just after updating a KnowngeneBean record in the database.
     *
     * @param bean the KnowngeneBean that was just updated
     */
    public void afterUpdate(KnowngeneBean bean) throws DAOException;


    /**
     * Invoked just before deleting a KnowngeneBean record in the database.
     *
     * @param bean the KnowngeneBean that is about to be deleted
     */
    public void beforeDelete(KnowngeneBean bean) throws DAOException;


    /**
     * Invoked just after deleting a KnowngeneBean record in the database.
     *
     * @param bean the KnowngeneBean that was just deleted
     */
    public void afterDelete(KnowngeneBean bean) throws DAOException;

}
