// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import java.util.Comparator;


/**
 * Comparator class is used to sort the MirnatorStatisticBean objects.
 * @author sql2java
 */
@SuppressWarnings("rawtypes")
public class MirnatorStatisticComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for MirnatorStatisticComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new MirnatorStatisticComparator(MirnatorStatisticManager.ID_STATISTIC_TEST_DESIGN, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>MirnatorStatisticManager.ID_STATISTIC_TEST_DESIGN
     *   <li>MirnatorStatisticManager.ID_STATISTIC_RR
     *   <li>MirnatorStatisticManager.ID_STATISTIC_TT
     *   <li>MirnatorStatisticManager.ID_STATISTIC_MW
     *   <li>MirnatorStatisticManager.ID_STATISTIC_MIRNA
     *   <li>MirnatorStatisticManager.ID_STATISTIC_ARRAY_ID
     *   <li>MirnatorStatisticManager.ID_STATISTIC_ID
     * </ul>
     */
    public MirnatorStatisticComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for MirnatorStatisticComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new MirnatorStatisticComparator(MirnatorStatisticManager.ID_STATISTIC_TEST_DESIGN, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>MirnatorStatisticManager.ID_STATISTIC_TEST_DESIGN
     *   <li>MirnatorStatisticManager.ID_STATISTIC_RR
     *   <li>MirnatorStatisticManager.ID_STATISTIC_TT
     *   <li>MirnatorStatisticManager.ID_STATISTIC_MW
     *   <li>MirnatorStatisticManager.ID_STATISTIC_MIRNA
     *   <li>MirnatorStatisticManager.ID_STATISTIC_ARRAY_ID
     *   <li>MirnatorStatisticManager.ID_STATISTIC_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public MirnatorStatisticComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        MirnatorStatisticBean b1 = (MirnatorStatisticBean)pObj1;
        MirnatorStatisticBean b2 = (MirnatorStatisticBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case MirnatorStatisticManager.ID_STATISTIC_TEST_DESIGN:
                if (b1.getStatisticTestDesign() == null && b2.getStatisticTestDesign() != null) {
                    iReturn = -1;
                } else if (b1.getStatisticTestDesign() == null && b2.getStatisticTestDesign() == null) {
                    iReturn = 0;
                } else if (b1.getStatisticTestDesign() != null && b2.getStatisticTestDesign() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getStatisticTestDesign().compareTo(b2.getStatisticTestDesign());
                }
                break;
            case MirnatorStatisticManager.ID_STATISTIC_RR:
                if (b1.getStatisticRr() == null && b2.getStatisticRr() != null) {
                    iReturn = -1;
                } else if (b1.getStatisticRr() == null && b2.getStatisticRr() == null) {
                    iReturn = 0;
                } else if (b1.getStatisticRr() != null && b2.getStatisticRr() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getStatisticRr().compareTo(b2.getStatisticRr());
                }
                break;
            case MirnatorStatisticManager.ID_STATISTIC_TT:
                if (b1.getStatisticTt() == null && b2.getStatisticTt() != null) {
                    iReturn = -1;
                } else if (b1.getStatisticTt() == null && b2.getStatisticTt() == null) {
                    iReturn = 0;
                } else if (b1.getStatisticTt() != null && b2.getStatisticTt() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getStatisticTt().compareTo(b2.getStatisticTt());
                }
                break;
            case MirnatorStatisticManager.ID_STATISTIC_MW:
                if (b1.getStatisticMw() == null && b2.getStatisticMw() != null) {
                    iReturn = -1;
                } else if (b1.getStatisticMw() == null && b2.getStatisticMw() == null) {
                    iReturn = 0;
                } else if (b1.getStatisticMw() != null && b2.getStatisticMw() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getStatisticMw().compareTo(b2.getStatisticMw());
                }
                break;
            case MirnatorStatisticManager.ID_STATISTIC_MIRNA:
                if (b1.getStatisticMirna() == null && b2.getStatisticMirna() != null) {
                    iReturn = -1;
                } else if (b1.getStatisticMirna() == null && b2.getStatisticMirna() == null) {
                    iReturn = 0;
                } else if (b1.getStatisticMirna() != null && b2.getStatisticMirna() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getStatisticMirna().compareTo(b2.getStatisticMirna());
                }
                break;
            case MirnatorStatisticManager.ID_STATISTIC_ARRAY_ID:
                if (b1.getStatisticArrayId() == null && b2.getStatisticArrayId() != null) {
                    iReturn = -1;
                } else if (b1.getStatisticArrayId() == null && b2.getStatisticArrayId() == null) {
                    iReturn = 0;
                } else if (b1.getStatisticArrayId() != null && b2.getStatisticArrayId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getStatisticArrayId().compareTo(b2.getStatisticArrayId());
                }
                break;
            case MirnatorStatisticManager.ID_STATISTIC_ID:
                if (b1.getStatisticId() == null && b2.getStatisticId() != null) {
                    iReturn = -1;
                } else if (b1.getStatisticId() == null && b2.getStatisticId() == null) {
                    iReturn = 0;
                } else if (b1.getStatisticId() != null && b2.getStatisticId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getStatisticId().compareTo(b2.getStatisticId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
