// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import mirnator.sql2java.exception.DAOException;

/**
 * Listener that is notified of mirnator_statistic table changes.
 * @author sql2java
 */
public interface MirnatorStatisticListener
{
    /**
     * Invoked just before inserting a MirnatorStatisticBean record into the database.
     *
     * @param bean the MirnatorStatisticBean that is about to be inserted
     */
    public void beforeInsert(MirnatorStatisticBean bean) throws DAOException;


    /**
     * Invoked just after a MirnatorStatisticBean record is inserted in the database.
     *
     * @param bean the MirnatorStatisticBean that was just inserted
     */
    public void afterInsert(MirnatorStatisticBean bean) throws DAOException;


    /**
     * Invoked just before updating a MirnatorStatisticBean record in the database.
     *
     * @param bean the MirnatorStatisticBean that is about to be updated
     */
    public void beforeUpdate(MirnatorStatisticBean bean) throws DAOException;


    /**
     * Invoked just after updating a MirnatorStatisticBean record in the database.
     *
     * @param bean the MirnatorStatisticBean that was just updated
     */
    public void afterUpdate(MirnatorStatisticBean bean) throws DAOException;


    /**
     * Invoked just before deleting a MirnatorStatisticBean record in the database.
     *
     * @param bean the MirnatorStatisticBean that is about to be deleted
     */
    public void beforeDelete(MirnatorStatisticBean bean) throws DAOException;


    /**
     * Invoked just after deleting a MirnatorStatisticBean record in the database.
     *
     * @param bean the MirnatorStatisticBean that was just deleted
     */
    public void afterDelete(MirnatorStatisticBean bean) throws DAOException;

}
