// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import java.util.Comparator;


/**
 * Comparator class is used to sort the MreTypeBean objects.
 * @author sql2java
 */
@SuppressWarnings("rawtypes")
public class MreTypeComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for MreTypeComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new MreTypeComparator(MreTypeManager.ID_DESCRIPTION, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>MreTypeManager.ID_DESCRIPTION
     *   <li>MreTypeManager.ID_MRE_TYPE_ID
     * </ul>
     */
    public MreTypeComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for MreTypeComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new MreTypeComparator(MreTypeManager.ID_DESCRIPTION, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>MreTypeManager.ID_DESCRIPTION
     *   <li>MreTypeManager.ID_MRE_TYPE_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public MreTypeComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        MreTypeBean b1 = (MreTypeBean)pObj1;
        MreTypeBean b2 = (MreTypeBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case MreTypeManager.ID_DESCRIPTION:
                if (b1.getDescription() == null && b2.getDescription() != null) {
                    iReturn = -1;
                } else if (b1.getDescription() == null && b2.getDescription() == null) {
                    iReturn = 0;
                } else if (b1.getDescription() != null && b2.getDescription() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getDescription().compareTo(b2.getDescription());
                }
                break;
            case MreTypeManager.ID_MRE_TYPE_ID:
                if (b1.getMreTypeId() == null && b2.getMreTypeId() != null) {
                    iReturn = -1;
                } else if (b1.getMreTypeId() == null && b2.getMreTypeId() == null) {
                    iReturn = 0;
                } else if (b1.getMreTypeId() != null && b2.getMreTypeId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getMreTypeId().compareTo(b2.getMreTypeId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
