// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;

import mirnator.sql2java.GeneratedBean;

import org.apache.commons.lang.builder.CompareToBuilder;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

/**
 * MreTypeBean is a mapping of mre_type Table.
 * @author sql2java
*/
public class MreTypeBean
    implements Serializable, GeneratedBean
{
	private static final long serialVersionUID = 3727999563761960587L;
	
    private String description;
    private boolean descriptionIsModified = false;
    private boolean descriptionIsInitialized = false;

    private Integer mreTypeId;
    private boolean mreTypeIdIsModified = false;
    private boolean mreTypeIdIsInitialized = false;

    private boolean _isNew = true;

    /**
     * Prefered methods to create a MreTypeBean is via the createMreTypeBean method in MreTypeManager or
     * via the factory class MreTypeFactory create method
     */
    protected MreTypeBean()
    {
    }

    /**
     * Getter method for description.
     * <br>
     * Meta Data Information (in progress):
     * <ul>
     * <li>full name: mre_type.description</li>
     * <li>column size: 2147483647</li>
     * <li>jdbc type returned by the driver: Types.VARCHAR</li>
     * </ul>
     *
     * @return the value of description
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Setter method for description.
     * <br>
     * The new value is set only if compareTo() says it is different,
     * or if one of either the new value or the current value is null.
     * In case the new value is different, it is set and the field is marked as 'modified'.
     *
     * @param newVal the new value to be assigned to description
     */
    public void setDescription(String newVal)
    {
        if ((newVal != null && description != null && (newVal.compareTo(description) == 0)) ||
            (newVal == null && description == null && descriptionIsInitialized)) {
            return;
        }
        description = newVal;
        descriptionIsModified = true;
        descriptionIsInitialized = true;
    }

    /**
     * Determines if the description has been modified.
     *
     * @return true if the field has been modified, false if the field has not been modified
     */
    public boolean isDescriptionModified()
    {
        return descriptionIsModified;
    }

    /**
     * Determines if the description has been initialized.
     * <br>
     * It is useful to determine if a field is null on purpose or just because it has not been initialized.
     *
     * @return true if the field has been initialized, false otherwise
     */
    public boolean isDescriptionInitialized()
    {
        return descriptionIsInitialized;
    }

    /**
     * Getter method for mreTypeId.
     * <br>
     * PRIMARY KEY.<br>
     * Meta Data Information (in progress):
     * <ul>
     * <li>full name: mre_type.mre_type_id</li>
     * <li> imported key: mre.mre_type_ref</li>
     * <li>column size: 10</li>
     * <li>jdbc type returned by the driver: Types.INTEGER</li>
     * </ul>
     *
     * @return the value of mreTypeId
     */
    public Integer getMreTypeId()
    {
        return mreTypeId;
    }

    /**
     * Setter method for mreTypeId.
     * <br>
     * The new value is set only if compareTo() says it is different,
     * or if one of either the new value or the current value is null.
     * In case the new value is different, it is set and the field is marked as 'modified'.
     *
     * @param newVal the new value to be assigned to mreTypeId
     */
    public void setMreTypeId(Integer newVal)
    {
        if ((newVal != null && mreTypeId != null && (newVal.compareTo(mreTypeId) == 0)) ||
            (newVal == null && mreTypeId == null && mreTypeIdIsInitialized)) {
            return;
        }
        mreTypeId = newVal;
        mreTypeIdIsModified = true;
        mreTypeIdIsInitialized = true;
    }

    /**
     * Setter method for mreTypeId.
     * <br>
     * Convenient for those who do not want to deal with Objects for primary types.
     *
     * @param newVal the new value to be assigned to mreTypeId
     */
    public void setMreTypeId(int newVal)
    {
        setMreTypeId(new Integer(newVal));
    }

    /**
     * Determines if the mreTypeId has been modified.
     *
     * @return true if the field has been modified, false if the field has not been modified
     */
    public boolean isMreTypeIdModified()
    {
        return mreTypeIdIsModified;
    }

    /**
     * Determines if the mreTypeId has been initialized.
     * <br>
     * It is useful to determine if a field is null on purpose or just because it has not been initialized.
     *
     * @return true if the field has been initialized, false otherwise
     */
    public boolean isMreTypeIdInitialized()
    {
        return mreTypeIdIsInitialized;
    }

    /**
     * Determines if the current object is new.
     *
     * @return true if the current object is new, false if the object is not new
     */
    public boolean isNew()
    {
        return _isNew;
    }

    /**
     * Specifies to the object if it has been set as new.
     *
     * @param isNew the boolean value to be assigned to the isNew field
     */
    public void isNew(boolean isNew)
    {
        this._isNew = isNew;
    }

    /**
     * Determines if the object has been modified since the last time this method was called.
     * <br>
     * We can also determine if this object has ever been modified since its creation.
     *
     * @return true if the object has been modified, false if the object has not been modified
     */
    public boolean isModified()
    {
        return descriptionIsModified 		|| mreTypeIdIsModified  ;
    }

    /**
     * Resets the object modification status to 'not modified'.
     */
    public void resetIsModified()
    {
        descriptionIsModified = false;
        mreTypeIdIsModified = false;
    }

    /**
     * Copies the passed bean into the current bean.
     *
     * @param bean the bean to copy into the current bean
     */
    public void copy(MreTypeBean bean)
    {
        setDescription(bean.getDescription());
        setMreTypeId(bean.getMreTypeId());
    }

    /**
     * return a dictionnary of the object
     */
    public Map<String,String> getDictionnary()
    {
        Map<String,String> dictionnary = new HashMap<String,String>();
        dictionnary.put("description", getDescription() == null ? "" : getDescription().toString());
        dictionnary.put("mre_type_id", getMreTypeId() == null ? "" : getMreTypeId().toString());
        return dictionnary;
    }

    /**
     * return a dictionnary of the pk columns
     */
    public Map<String,String> getPkDictionnary()
    {
        Map<String,String> dictionnary = new HashMap<String,String>();
        dictionnary.put("mre_type_id", getMreTypeId() == null ? "" : getMreTypeId().toString());
        return dictionnary;
    }

    /**
     * return a the value string representation of the given field
     */
    public String getValue(String column)
    {
        if (null == column || "".equals(column)) {
            return "";
        } else if ("description".equalsIgnoreCase(column) || "description".equalsIgnoreCase(column)) {
            return getDescription() == null ? "" : getDescription().toString();
        } else if ("mre_type_id".equalsIgnoreCase(column) || "mreTypeId".equalsIgnoreCase(column)) {
            return getMreTypeId() == null ? "" : getMreTypeId().toString();
        }
        return "";
    }

    /**
	 * @see java.lang.Object#equals(Object)
	 */
	public boolean equals(Object object)
	{
		if (!(object instanceof MreTypeBean)) {
			return false;
		}

		MreTypeBean obj = (MreTypeBean) object;
		return new EqualsBuilder()
            .append(getDescription(), obj.getDescription())
            .append(getMreTypeId(), obj.getMreTypeId())
            .isEquals();
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode()
	{
		return new HashCodeBuilder(-82280557, -700257973)
            .append(getDescription())
            .append(getMreTypeId())
            .toHashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	public String toString()
	{
	    return toString(ToStringStyle.MULTI_LINE_STYLE);
	}

	/**
	 * you can use the following styles:
	 * <li>ToStringStyle.DEFAULT_STYLE</li>
	 * <li>ToStringStyle.MULTI_LINE_STYLE</li>
     * <li>ToStringStyle.NO_FIELD_NAMES_STYLE</li>
     * <li>ToStringStyle.SHORT_PREFIX_STYLE</li>
     * <li>ToStringStyle.SIMPLE_STYLE</li>
	 */
	public String toString(ToStringStyle style) {
		return new ToStringBuilder(this, style)
            .append("description", getDescription())
            .append("mre_type_id", getMreTypeId())
            .toString();
	}


    public int compareTo(Object object)
    {
        MreTypeBean obj = (MreTypeBean) object;
        return new CompareToBuilder()
            .append(getDescription(), obj.getDescription())
            .append(getMreTypeId(), obj.getMreTypeId())
            .toComparison();
   }
}
