// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import mirnator.sql2java.exception.DAOException;

/**
 * Listener that is notified of mre_type table changes.
 * @author sql2java
 */
public interface MreTypeListener
{
    /**
     * Invoked just before inserting a MreTypeBean record into the database.
     *
     * @param bean the MreTypeBean that is about to be inserted
     */
    public void beforeInsert(MreTypeBean bean) throws DAOException;


    /**
     * Invoked just after a MreTypeBean record is inserted in the database.
     *
     * @param bean the MreTypeBean that was just inserted
     */
    public void afterInsert(MreTypeBean bean) throws DAOException;


    /**
     * Invoked just before updating a MreTypeBean record in the database.
     *
     * @param bean the MreTypeBean that is about to be updated
     */
    public void beforeUpdate(MreTypeBean bean) throws DAOException;


    /**
     * Invoked just after updating a MreTypeBean record in the database.
     *
     * @param bean the MreTypeBean that was just updated
     */
    public void afterUpdate(MreTypeBean bean) throws DAOException;


    /**
     * Invoked just before deleting a MreTypeBean record in the database.
     *
     * @param bean the MreTypeBean that is about to be deleted
     */
    public void beforeDelete(MreTypeBean bean) throws DAOException;


    /**
     * Invoked just after deleting a MreTypeBean record in the database.
     *
     * @param bean the MreTypeBean that was just deleted
     */
    public void afterDelete(MreTypeBean bean) throws DAOException;

}
