// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import mirnator.sql2java.exception.DAOException;

/**
 * Listener that is notified of test_design table changes.
 * @author sql2java
 */
public interface TestDesignListener
{
    /**
     * Invoked just before inserting a TestDesignBean record into the database.
     *
     * @param bean the TestDesignBean that is about to be inserted
     */
    public void beforeInsert(TestDesignBean bean) throws DAOException;


    /**
     * Invoked just after a TestDesignBean record is inserted in the database.
     *
     * @param bean the TestDesignBean that was just inserted
     */
    public void afterInsert(TestDesignBean bean) throws DAOException;


    /**
     * Invoked just before updating a TestDesignBean record in the database.
     *
     * @param bean the TestDesignBean that is about to be updated
     */
    public void beforeUpdate(TestDesignBean bean) throws DAOException;


    /**
     * Invoked just after updating a TestDesignBean record in the database.
     *
     * @param bean the TestDesignBean that was just updated
     */
    public void afterUpdate(TestDesignBean bean) throws DAOException;


    /**
     * Invoked just before deleting a TestDesignBean record in the database.
     *
     * @param bean the TestDesignBean that is about to be deleted
     */
    public void beforeDelete(TestDesignBean bean) throws DAOException;


    /**
     * Invoked just after deleting a TestDesignBean record in the database.
     *
     * @param bean the TestDesignBean that was just deleted
     */
    public void afterDelete(TestDesignBean bean) throws DAOException;

}
