// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import java.util.Comparator;


/**
 * Comparator class is used to sort the TestDesignBean objects.
 * @author sql2java
 */
@SuppressWarnings("rawtypes")
public class TestDesignComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for TestDesignComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TestDesignComparator(TestDesignManager.ID_TEST_DESIGN, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TestDesignManager.ID_TEST_DESIGN
     *   <li>TestDesignManager.ID_TEST_ID
     * </ul>
     */
    public TestDesignComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for TestDesignComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new TestDesignComparator(TestDesignManager.ID_TEST_DESIGN, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>TestDesignManager.ID_TEST_DESIGN
     *   <li>TestDesignManager.ID_TEST_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public TestDesignComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        TestDesignBean b1 = (TestDesignBean)pObj1;
        TestDesignBean b2 = (TestDesignBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case TestDesignManager.ID_TEST_DESIGN:
                if (b1.getTestDesign() == null && b2.getTestDesign() != null) {
                    iReturn = -1;
                } else if (b1.getTestDesign() == null && b2.getTestDesign() == null) {
                    iReturn = 0;
                } else if (b1.getTestDesign() != null && b2.getTestDesign() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTestDesign().compareTo(b2.getTestDesign());
                }
                break;
            case TestDesignManager.ID_TEST_ID:
                if (b1.getTestId() == null && b2.getTestId() != null) {
                    iReturn = -1;
                } else if (b1.getTestId() == null && b2.getTestId() == null) {
                    iReturn = 0;
                } else if (b1.getTestId() != null && b2.getTestId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getTestId().compareTo(b2.getTestId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
