// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import java.util.Comparator;


/**
 * Comparator class is used to sort the XrefBean objects.
 * @author sql2java
 */
@SuppressWarnings("rawtypes")
public class XrefComparator implements Comparator
{
    /**
     * Holds the field on which the comparison is performed.
     */
    private int iType;
    /**
     * Value that will contain the information about the order of the sort: normal or reversal.
     */
    private boolean bReverse;

    /**
     * Constructor class for XrefComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new XrefComparator(XrefManager.ID_DESCRIPTION, bReverse));<code>
     *
     * @param iType the field from which you want to sort
     * <br>
     * Possible values are:
     * <ul>
     *   <li>XrefManager.ID_DESCRIPTION
     *   <li>XrefManager.ID_PROTACC
     *   <li>XrefManager.ID_REFSEQ
     *   <li>XrefManager.ID_GENESYMBOL
     *   <li>XrefManager.ID_SP_DISPLAY_ID
     *   <li>XrefManager.ID_SP_ID
     *   <li>XrefManager.ID_MRNA
     *   <li>XrefManager.ID_KNOWNGENE_REF
     *   <li>XrefManager.ID_XREF_ID
     * </ul>
     */
    public XrefComparator(int iType)
    {
        this(iType, false);
    }

    /**
     * Constructor class for XrefComparator.
     * <br>
     * Example:
     * <br>
     * <code>Arrays.sort(pArray, new XrefComparator(XrefManager.ID_DESCRIPTION, bReverse));<code>
     *
     * @param iType the field from which you want to sort.
     * <br>
     * Possible values are:
     * <ul>
     *   <li>XrefManager.ID_DESCRIPTION
     *   <li>XrefManager.ID_PROTACC
     *   <li>XrefManager.ID_REFSEQ
     *   <li>XrefManager.ID_GENESYMBOL
     *   <li>XrefManager.ID_SP_DISPLAY_ID
     *   <li>XrefManager.ID_SP_ID
     *   <li>XrefManager.ID_MRNA
     *   <li>XrefManager.ID_KNOWNGENE_REF
     *   <li>XrefManager.ID_XREF_ID
     * </ul>
     *
     * @param bReverse set this value to true, if you want to reverse the sorting results
     */
    public XrefComparator(int iType, boolean bReverse)
    {
        this.iType = iType;
        this.bReverse = bReverse;
    }

    /**
     * Implementation of the compare method.
     */
    public int compare(Object pObj1, Object pObj2)
    {
        XrefBean b1 = (XrefBean)pObj1;
        XrefBean b2 = (XrefBean)pObj2;
        int iReturn = 0;
        switch(iType)
        {
            case XrefManager.ID_DESCRIPTION:
                if (b1.getDescription() == null && b2.getDescription() != null) {
                    iReturn = -1;
                } else if (b1.getDescription() == null && b2.getDescription() == null) {
                    iReturn = 0;
                } else if (b1.getDescription() != null && b2.getDescription() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getDescription().compareTo(b2.getDescription());
                }
                break;
            case XrefManager.ID_PROTACC:
                if (b1.getProtacc() == null && b2.getProtacc() != null) {
                    iReturn = -1;
                } else if (b1.getProtacc() == null && b2.getProtacc() == null) {
                    iReturn = 0;
                } else if (b1.getProtacc() != null && b2.getProtacc() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getProtacc().compareTo(b2.getProtacc());
                }
                break;
            case XrefManager.ID_REFSEQ:
                if (b1.getRefseq() == null && b2.getRefseq() != null) {
                    iReturn = -1;
                } else if (b1.getRefseq() == null && b2.getRefseq() == null) {
                    iReturn = 0;
                } else if (b1.getRefseq() != null && b2.getRefseq() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getRefseq().compareTo(b2.getRefseq());
                }
                break;
            case XrefManager.ID_GENESYMBOL:
                if (b1.getGenesymbol() == null && b2.getGenesymbol() != null) {
                    iReturn = -1;
                } else if (b1.getGenesymbol() == null && b2.getGenesymbol() == null) {
                    iReturn = 0;
                } else if (b1.getGenesymbol() != null && b2.getGenesymbol() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getGenesymbol().compareTo(b2.getGenesymbol());
                }
                break;
            case XrefManager.ID_SP_DISPLAY_ID:
                if (b1.getSpDisplayId() == null && b2.getSpDisplayId() != null) {
                    iReturn = -1;
                } else if (b1.getSpDisplayId() == null && b2.getSpDisplayId() == null) {
                    iReturn = 0;
                } else if (b1.getSpDisplayId() != null && b2.getSpDisplayId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getSpDisplayId().compareTo(b2.getSpDisplayId());
                }
                break;
            case XrefManager.ID_SP_ID:
                if (b1.getSpId() == null && b2.getSpId() != null) {
                    iReturn = -1;
                } else if (b1.getSpId() == null && b2.getSpId() == null) {
                    iReturn = 0;
                } else if (b1.getSpId() != null && b2.getSpId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getSpId().compareTo(b2.getSpId());
                }
                break;
            case XrefManager.ID_MRNA:
                if (b1.getMrna() == null && b2.getMrna() != null) {
                    iReturn = -1;
                } else if (b1.getMrna() == null && b2.getMrna() == null) {
                    iReturn = 0;
                } else if (b1.getMrna() != null && b2.getMrna() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getMrna().compareTo(b2.getMrna());
                }
                break;
            case XrefManager.ID_KNOWNGENE_REF:
                if (b1.getKnowngeneRef() == null && b2.getKnowngeneRef() != null) {
                    iReturn = -1;
                } else if (b1.getKnowngeneRef() == null && b2.getKnowngeneRef() == null) {
                    iReturn = 0;
                } else if (b1.getKnowngeneRef() != null && b2.getKnowngeneRef() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getKnowngeneRef().compareTo(b2.getKnowngeneRef());
                }
                break;
            case XrefManager.ID_XREF_ID:
                if (b1.getXrefId() == null && b2.getXrefId() != null) {
                    iReturn = -1;
                } else if (b1.getXrefId() == null && b2.getXrefId() == null) {
                    iReturn = 0;
                } else if (b1.getXrefId() != null && b2.getXrefId() == null) {
                    iReturn = 1;
                } else {
                    iReturn = b1.getXrefId().compareTo(b2.getXrefId());
                }
                break;
            default:
                throw new IllegalArgumentException("Type passed for the field is not supported");
        }

        return bReverse ? (-1 * iReturn) : iReturn;
    }}
