// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: org.postgresql.Driver
//
// Please help us improve this tool by reporting:
// - problems and suggestions to
//   http://sourceforge.net/tracker/?group_id=54687
// - feedbacks and ideas on
//   http://sourceforge.net/forum/forum.php?forum_id=182208
// ______________________________________________________

package mirnator.sql2java;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.List;
import java.util.ArrayList;

import mirnator.sql2java.Manager;
import mirnator.sql2java.exception.DAOException;
import mirnator.sql2java.exception.DataAccessException;
import mirnator.sql2java.exception.ObjectRetrievalException;
import mirnator.sql2java.KnowngeneBean;
import mirnator.sql2java.KnowngeneManager;

/**
 * Handles database calls (save, load, count, etc...) for the xref table.
 * @author sql2java
 */
public class XrefManager 
{

    /* set =QUERY for loadUsingTemplate */
    public static final int SEARCH_EXACT = 0;
    /* set %QUERY% for loadLikeTemplate */
    public static final int SEARCH_LIKE = 1;
    /* set %QUERY for loadLikeTemplate */
    public static final int SEARCH_STARTING_LIKE = 2;
    /* set QUERY% for loadLikeTemplate */
    public static final int SEARCH_ENDING_LIKE = 3;

    /**
     * Identify the description field.
     */
    public static final int ID_DESCRIPTION = 0;

    /**
     * Identify the protacc field.
     */
    public static final int ID_PROTACC = 1;

    /**
     * Identify the refseq field.
     */
    public static final int ID_REFSEQ = 2;

    /**
     * Identify the genesymbol field.
     */
    public static final int ID_GENESYMBOL = 3;

    /**
     * Identify the sp_display_id field.
     */
    public static final int ID_SP_DISPLAY_ID = 4;

    /**
     * Identify the sp_id field.
     */
    public static final int ID_SP_ID = 5;

    /**
     * Identify the mrna field.
     */
    public static final int ID_MRNA = 6;

    /**
     * Identify the knowngene_ref field.
     */
    public static final int ID_KNOWNGENE_REF = 7;

    /**
     * Identify the xref_id field.
     */
    public static final int ID_XREF_ID = 8;

    /**
     * Contains all the full fields of the xref table.
     */
    private static final String[] FULL_FIELD_NAMES =
    {
        "xref.description"
        ,"xref.protacc"
        ,"xref.refseq"
        ,"xref.genesymbol"
        ,"xref.sp_display_id"
        ,"xref.sp_id"
        ,"xref.mrna"
        ,"xref.knowngene_ref"
        ,"xref.xref_id"
    };

    /**
     * Contains all the fields of the xref table.
     */
    public static final String[] FIELD_NAMES =
    {
        "description"
        ,"protacc"
        ,"refseq"
        ,"genesymbol"
        ,"sp_display_id"
        ,"sp_id"
        ,"mrna"
        ,"knowngene_ref"
        ,"xref_id"
    };

    /**
     * Field that contains the comma separated fields of the xref table.
     */
    public static final String ALL_FULL_FIELDS = "xref.description"
                            + ",xref.protacc"
                            + ",xref.refseq"
                            + ",xref.genesymbol"
                            + ",xref.sp_display_id"
                            + ",xref.sp_id"
                            + ",xref.mrna"
                            + ",xref.knowngene_ref"
                            + ",xref.xref_id";

    /**
     * Field that contains the comma separated fields of the xref table.
     */
    public static final String ALL_FIELDS = "description"
                            + ",protacc"
                            + ",refseq"
                            + ",genesymbol"
                            + ",sp_display_id"
                            + ",sp_id"
                            + ",mrna"
                            + ",knowngene_ref"
                            + ",xref_id";

    private static XrefManager singleton = new XrefManager();

    /**
     * Get the XrefManager singleton.
     *
     * @return XrefManager
     */
    public static XrefManager getInstance()
    {
        return singleton;
    }


    /**
     * Creates a new XrefBean instance.
     *
     * @return the new XrefBean
     */
    public XrefBean createXrefBean()
    {
        return new XrefBean();
    }

    //////////////////////////////////////
    // PRIMARY KEY METHODS
    //////////////////////////////////////

    /**
     * Loads a XrefBean from the xref using its key fields.
     *
     * @param xrefId Integer - PK# 1
     * @return a unique XrefBean
     * @throws DAOException
     */
    //1
    public XrefBean loadByPrimaryKey(Integer xrefId) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuilder sql = new StringBuilder("SELECT " + ALL_FIELDS + " FROM xref WHERE xref_id=?");
            // System.out.println("loadByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (xrefId == null) { ps.setNull(1, Types.INTEGER); } else { Manager.setInteger(ps, 1, xrefId); }
            List<XrefBean> pReturn = this.loadByPreparedStatementAsList(ps);
            if (pReturn.size() == 0) {
                throw new ObjectRetrievalException();
            } else {
                return pReturn.get(0);
            }
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Deletes rows according to its keys.
     *
     * @param xrefId Integer - PK# 1
     * @return the number of deleted rows
     * @throws DAOException
     */
    //2
    public int deleteByPrimaryKey(Integer xrefId) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        try
        {
            c = this.getConnection();
            StringBuilder sql = new StringBuilder("DELETE FROM xref WHERE xref_id=?");
            // System.out.println("deleteByPrimaryKey: " + sql);
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            if (xrefId == null) { ps.setNull(1, Types.INTEGER); } else { Manager.setInteger(ps, 1, xrefId); }
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }


    //////////////////////////////////////
    // GET/SET FOREIGN KEY BEAN METHOD
    //////////////////////////////////////
    /**
     * Retrieves the KnowngeneBean object from the xref.knowngene_ref field.
     *
     * @param bean the XrefBean
     * @return the associated KnowngeneBean bean
     * @throws DAOException
     */
    //3.2 GET IMPORTED VALUES
    public KnowngeneBean getKnowngeneBean(XrefBean bean) throws DAOException
    {
        KnowngeneBean other = KnowngeneManager.getInstance().createKnowngeneBean();
        other.setGeneId(bean.getKnowngeneRef()); 
        bean.setKnowngeneBean(KnowngeneManager.getInstance().loadUniqueUsingTemplate(other)); 
        return bean.getKnowngeneBean();
    }

    /**
     * Associates the XrefBean object to the KnowngeneBean object.
     *
     * @param bean the XrefBean object to use
     * @param beanToSet the KnowngeneBean object to associate to the XrefBean
     * @return the associated KnowngeneBean bean
     * @throws Exception
     */
    //4.2 ADD IMPORTED VALUE
    public KnowngeneBean addKnowngeneBean(KnowngeneBean beanToSet, XrefBean bean) throws Exception
    {
        beanToSet.setGeneId(bean.getKnowngeneRef());
        return KnowngeneManager.getInstance().save(beanToSet);
    }

    /**
     * Associates the XrefBean object to the KnowngeneBean object.
     *
     * @param bean the XrefBean object to use
     * @param beanToSet the KnowngeneBean object to associate to the XrefBean
     * @return the associated KnowngeneBean bean
     * @throws Exception
     */
    //5.2 SET IMPORTED
    public KnowngeneBean setKnowngeneBean(XrefBean bean, KnowngeneBean beanToSet) throws Exception
    {
        bean.setKnowngeneRef(beanToSet.getGeneId());
        return KnowngeneManager.getInstance().save(beanToSet);
    }



    //////////////////////////////////////
    // LOAD ALL
    //////////////////////////////////////

    /**
     * Loads all the rows from xref.
     *
     * @return an array of XrefManager bean
     * @throws DAOException
     */
    //5
    public XrefBean[] loadAll() throws DAOException
    {
        return this.loadUsingTemplate(null);
    }

    /**
     * Loads all the rows from xref.
     *
     * @return a list of XrefManager bean
     * @throws DAOException
     */
    //5
    public List<XrefBean> loadAllAsList() throws DAOException
    {
        return this.loadUsingTemplateAsList(null);
    }


    /**
     * Loads the given number of rows from xref, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return an array of XrefManager bean
     * @throws DAOException
     */
    //6
    public XrefBean[] loadAll(int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(null, startRow, numRows);
    }

    /**
     * Loads the given number of rows from xref, given the start row.
     *
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return a list of XrefManager bean
     * @throws DAOException
     */
    //6
    public List<XrefBean> loadAllAsList(int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplateAsList(null, startRow, numRows);
    }

    //////////////////////////////////////
    // SQL 'WHERE' METHOD
    //////////////////////////////////////
    /**
     * Retrieves an array of XrefBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting XrefBean table
     * @throws DAOException
     */
    //7
    public XrefBean[] loadByWhere(String where) throws DAOException
    {
        return this.loadByWhere(where, null);
    }
    /**
     * Retrieves a list of XrefBean given a sql 'where' clause.
     *
     * @param where the sql 'where' clause
     * @return the resulting XrefBean table
     * @throws DAOException
     */
    //7
    public List<XrefBean> loadByWhereAsList(String where) throws DAOException
    {
        return this.loadByWhereAsList(where, null);
    }

    /**
     * Retrieves an array of XrefBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'WHERE' clause
     * @param fieldList array of field's ID
     * @return the resulting XrefBean table
     * @throws DAOException
     */
    //8
    public XrefBean[] loadByWhere(String where, int[] fieldList) throws DAOException
    {
        return this.loadByWhere(where, fieldList, 1, -1);
    }


    /**
     * Retrieves a list of XrefBean given a sql where clause, and a list of fields.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'WHERE' clause
     * @param fieldList array of field's ID
     * @return the resulting XrefBean table
     * @throws DAOException
     */
    //8
    public List<XrefBean> loadByWhereAsList(String where, int[] fieldList) throws DAOException
    {
        return this.loadByWhereAsList(where, fieldList, 1, -1);
    }

    /**
     * Retrieves an array of XrefBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting XrefBean table
     * @throws DAOException
     */
    //9
    public XrefBean[] loadByWhere(String where, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        return (XrefBean[]) this.loadByWhereAsList(where, fieldList, startRow, numRows).toArray(new XrefBean[0]);
    }

    /**
     * Retrieves a list of XrefBean given a sql where clause and a list of fields, and startRow and numRows.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the sql 'where' clause
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return the resulting XrefBean table
     * @throws DAOException
     */
    //9
    public List<XrefBean> loadByWhereAsList(String where, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        StringBuffer sql = new StringBuffer(128);
        if(fieldList == null) {
            sql.append("SELECT ").append(ALL_FIELDS).append(" FROM xref ").append(where);
        } else
        {
            sql.append("SELECT ");
            for(int i = 0; i < fieldList.length; i++)
            {
                if(i != 0) {
                    sql.append(",");
                }
                sql.append(FULL_FIELD_NAMES[fieldList[i]]);
            }
            sql.append(" FROM xref ");
            sql.append(where);
        }
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        // System.out.println("loadByWhere: " + sql);
        try
        {
            c = this.getConnection();
            st = c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            rs = st.executeQuery(sql.toString());
            return this.decodeResultSetAsList(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(st, rs);
            this.freeConnection(c);
        }
    }


    /**
     * Deletes all rows from xref table.
     * @return the number of deleted rows.
     * @throws DAOException
     */
    //10
    public int deleteAll() throws DAOException
    {
        return this.deleteByWhere("");
    }


    /**
     * Deletes rows from the xref table using a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     * <br>Attention, if 'WHERE' is omitted it will delete all records.
     *
     * @param where the sql 'where' clause
     * @return the number of deleted rows
     * @throws DAOException
     */
    //11
    public int deleteByWhere(String where) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;

        try
        {
            c = this.getConnection();
            StringBuilder sql = new StringBuilder("DELETE FROM xref " + where);
            // System.out.println("deleteByWhere: " + sql);
            ps = c.prepareStatement(sql.toString());
            return ps.executeUpdate();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    //_____________________________________________________________________
    //
    // SAVE
    //_____________________________________________________________________
    /**
     * Saves the XrefBean bean into the database.
     *
     * @param bean the XrefBean bean to be saved
     * @return the inserted or updated bean
     * @throws DAOException
     */
    //12
    public XrefBean save(XrefBean bean) throws DAOException
    {
        if (bean.isNew()) {
            return this.insert(bean);
        } else {
            return this.update(bean);
        }
    }

    /**
     * Insert the XrefBean bean into the database.
     *
     * @param bean the XrefBean bean to be saved
     * @return the inserted bean
     * @throws DAOException
     */
    //13
    public XrefBean insert(XrefBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (!bean.isNew()){
            return this.update(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuilder sql = null;

        try
        {
            c = this.getConnection();
            if (!bean.isXrefIdModified())
            {
                StringBuilder hint = new StringBuilder("SELECT nextval('xref_xref_id_SEQ')");
                // System.out.println("generatedKey : " + hint);

                ps = c.prepareStatement(hint.toString());
                ResultSet rs = null;
                try
                {
                    rs = ps.executeQuery();
                    if(rs.next()) {
                        bean.setXrefId(Manager.getInteger(rs, 1));
                    } else {
                        this.getManager().log("ATTENTION: Could not retrieve generated key!");
                    }
                }
                finally
                {
                    this.getManager().close(ps, rs);
                    ps=null;
                }
            }
            this.beforeInsert(bean); // listener callback
            int _dirtyCount = 0;
            sql = new StringBuilder("INSERT into xref (");

            if (bean.isDescriptionModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("description");
                _dirtyCount++;
            }

            if (bean.isProtaccModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("protacc");
                _dirtyCount++;
            }

            if (bean.isRefseqModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("refseq");
                _dirtyCount++;
            }

            if (bean.isGenesymbolModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("genesymbol");
                _dirtyCount++;
            }

            if (bean.isSpDisplayIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("sp_display_id");
                _dirtyCount++;
            }

            if (bean.isSpIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("sp_id");
                _dirtyCount++;
            }

            if (bean.isMrnaModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("mrna");
                _dirtyCount++;
            }

            if (bean.isKnowngeneRefModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("knowngene_ref");
                _dirtyCount++;
            }

            if (bean.isXrefIdModified()) {
                if (_dirtyCount>0) {
                    sql.append(",");
                }
                sql.append("xref_id");
                _dirtyCount++;
            }

            sql.append(") values (");
            if(_dirtyCount > 0) {
                sql.append("?");
                for(int i = 1; i < _dirtyCount; i++) {
                    sql.append(",?");
                }
            }
            sql.append(")");


            // System.out.println("insert : " + sql.toString());

            ps = c.prepareStatement(sql.toString(), ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);

            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            ps.executeUpdate();

            bean.isNew(false);
            bean.resetIsModified();
            this.afterInsert(bean); // listener callback
            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Update the XrefBean bean record in the database according to the changes.
     *
     * @param bean the XrefBean bean to be updated
     * @return the updated bean
     * @throws DAOException
     */
    //14
    public XrefBean update(XrefBean bean) throws DAOException
    {
        // mini checks
        if (!bean.isModified()) {
            return bean; // should not we log something ?
        }
        if (bean.isNew()){
            return this.insert(bean);
        }

        Connection c = null;
        PreparedStatement ps = null;
        StringBuilder sql = null;

        try
        {
            c = this.getConnection();

            this.beforeUpdate(bean); // listener callback
            sql = new StringBuilder("UPDATE xref SET ");
            boolean useComma=false;

            if (bean.isDescriptionModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("description=?");
            }

            if (bean.isProtaccModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("protacc=?");
            }

            if (bean.isRefseqModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("refseq=?");
            }

            if (bean.isGenesymbolModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("genesymbol=?");
            }

            if (bean.isSpDisplayIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("sp_display_id=?");
            }

            if (bean.isSpIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("sp_id=?");
            }

            if (bean.isMrnaModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("mrna=?");
            }

            if (bean.isKnowngeneRefModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("knowngene_ref=?");
            }

            if (bean.isXrefIdModified()) {
                if (useComma) {
                    sql.append(", ");
                } else {
                    useComma=true;
                }
                sql.append("xref_id=?");
            }
            sql.append(" WHERE ");
            sql.append("xref_id=?");
            // System.out.println("update : " + sql.toString());
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);

            int _dirtyCount = this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            if (_dirtyCount == 0) {
                // System.out.println("The bean to look is not initialized... do not update.");
                return bean;
            }

            if (bean.getXrefId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getXrefId()); }
            ps.executeUpdate();
            bean.resetIsModified();
            this.afterUpdate(bean); // listener callback

            return bean;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            sql = null;
            this.getManager().close(ps);
            this.freeConnection(c);
        }
    }

    /**
     * Saves an array of XrefBean beans into the database.
     *
     * @param beans the XrefBean bean table to be saved
     * @return the saved XrefBean array.
     * @throws DAOException
     */
    //15
    public XrefBean[] save(XrefBean[] beans) throws DAOException
    {
        for (XrefBean bean : beans) 
        {
            this.save(bean);
        }
        return beans;
    }

    /**
     * Saves a list of XrefBean beans into the database.
     *
     * @param beans the XrefBean bean table to be saved
     * @return the saved XrefBean array.
     * @throws DAOException
     */
    //15
    public List<XrefBean> save(List<XrefBean> beans) throws DAOException
    {
        for (XrefBean bean : beans) 
        {
            this.save(bean);
        }
        return beans;
    }

    /**
     * Insert an array of XrefBean beans into the database.
     *
     * @param beans the XrefBean bean table to be inserted
     * @return the saved XrefBean array.
     * @throws DAOException
     */
    //16
    public XrefBean[] insert(XrefBean[] beans) throws DAOException
    {
        return this.save(beans);
    }

    /**
     * Insert a list of XrefBean beans into the database.
     *
     * @param beans the XrefBean bean table to be inserted
     * @return the saved XrefBean array.
     * @throws DAOException
     */
    //16
    public List<XrefBean> insert(List<XrefBean> beans) throws DAOException
    {
        return this.save(beans);
    }

    /**
     * Updates an array of XrefBean beans into the database.
     *
     * @param beans the XrefBean bean table to be inserted
     * @return the saved XrefBean array.
     * @throws DAOException
     */
    //17
    public XrefBean[] update(XrefBean[] beans) throws DAOException
    {
        return this.save(beans);
    }

    /**
     * Updates a list of XrefBean beans into the database.
     *
     * @param beans the XrefBean bean table to be inserted
     * @return the saved XrefBean array.
     * @throws DAOException
     */
    //17
    public List<XrefBean> update(List<XrefBean> beans) throws DAOException
    {
        return this.save(beans);
    }
    

    //_____________________________________________________________________
    //
    // USING TEMPLATE
    //_____________________________________________________________________
    /**
     * Loads a unique XrefBean bean from a template one giving a c
     *
     * @param bean the XrefBean bean to look for
     * @return the bean matching the template
     * @throws DAOException
     */
    //18
    public XrefBean loadUniqueUsingTemplate(XrefBean bean) throws DAOException
    {
         XrefBean[] beans = this.loadUsingTemplate(bean);
         if (beans.length == 0) {
             return null;
         }
         if (beans.length > 1) {
             throw new ObjectRetrievalException("More than one element !!");
         }
         return beans[0];
     }

    /**
     * Loads an array of XrefBean from a template one.
     *
     * @param bean the XrefBean template to look for
     * @return all the XrefBean matching the template
     * @throws DAOException
     */
    //19
    public XrefBean[] loadUsingTemplate(XrefBean bean) throws DAOException
    {
        return this.loadUsingTemplate(bean, 1, -1);
    }

    /**
     * Loads a list of XrefBean from a template one.
     *
     * @param bean the XrefBean template to look for
     * @return all the XrefBean matching the template
     * @throws DAOException
     */
    //19
    public List<XrefBean> loadUsingTemplateAsList(XrefBean bean) throws DAOException
    {
        return this.loadUsingTemplateAsList(bean, 1, -1);
    }

    /**
     * Loads an array of XrefBean from a template one, given the start row and number of rows.
     *
     * @param bean the XrefBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the XrefBean matching the template
     * @throws DAOException
     */
    //20
    public XrefBean[] loadUsingTemplate(XrefBean bean, int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * Loads a list of XrefBean from a template one, given the start row and number of rows.
     *
     * @param bean the XrefBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return all the XrefBean matching the template
     * @throws DAOException
     */
    //20
    public List<XrefBean> loadUsingTemplateAsList(XrefBean bean, int startRow, int numRows) throws DAOException
    {
        return this.loadUsingTemplateAsList(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * Loads an array of XrefBean from a template one, given the start row and number of rows.
     *
     * @param bean the XrefBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return all the XrefBean matching the template
     * @throws DAOException
     */
    //20
    public XrefBean[] loadUsingTemplate(XrefBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
    	return (XrefBean[])this.loadUsingTemplateAsList(bean, startRow, numRows, searchType).toArray(new XrefBean[0]);
    }

    /**
     * Loads a list of XrefBean from a template one, given the start row and number of rows.
     *
     * @param bean the XrefBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return all the XrefBean matching the template
     * @throws DAOException
     */
    //20
    public List<XrefBean> loadUsingTemplateAsList(XrefBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        // System.out.println("loadUsingTemplate startRow:" + startRow + ", numRows:" + numRows + ", searchType:" + searchType);
        Connection c = null;
        PreparedStatement ps = null;
        StringBuffer sql = new StringBuffer(128);
        sql.append("SELECT ").append(ALL_FIELDS).append(" FROM xref ");
        StringBuilder sqlWhere = new StringBuilder("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, searchType) > 0)
            {
                sql.append(" WHERE ").append(sqlWhere);
            }
            else
            {
                // System.out.println("The bean to look is not initialized... loading all");
            }
            // System.out.println("loadUsingTemplate: " + sql.toString());

            c = this.getConnection();
            int scrollType = ResultSet.TYPE_SCROLL_INSENSITIVE;
            if (startRow != 1) {
                scrollType = ResultSet.TYPE_SCROLL_SENSITIVE;
            }
            ps = c.prepareStatement(sql.toString(),
                                    scrollType,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            ps.executeQuery();
            return this.loadByPreparedStatementAsList(ps, null, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new ObjectRetrievalException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    /**
     * Deletes rows using a XrefBean template.
     *
     * @param bean the XrefBean object(s) to be deleted
     * @return the number of deleted objects
     * @throws DAOException
     */
    //21
    public int deleteUsingTemplate(XrefBean bean) throws DAOException
    {
        if (bean.isXrefIdInitialized()) {
            return this.deleteByPrimaryKey(bean.getXrefId());
        }
        Connection c = null;
        PreparedStatement ps = null;
        StringBuilder sql = new StringBuilder("DELETE FROM xref ");
        StringBuilder sqlWhere = new StringBuilder("");

        try
        {
            this.beforeDelete(bean); // listener callback
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0)
            {
                sql.append(" WHERE ").append(sqlWhere);
            }
            else
            {
                // System.out.println("The bean to look is not initialized... deleting all");
            }
            // System.out.println("deleteUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, SEARCH_EXACT);

            int _rows = ps.executeUpdate();
            this.afterDelete(bean); // listener callback
            return _rows;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }



    //_____________________________________________________________________
    //
    // COUNT
    //_____________________________________________________________________

    /**
     * Retrieves the number of rows of the table xref.
     *
     * @return the number of rows returned
     * @throws DAOException
     */
    //24
    public int countAll() throws DAOException
    {
        return this.countWhere("");
    }

    /**
     * Retrieves the number of rows of the table xref with a 'where' clause.
     * It is up to you to pass the 'WHERE' in your where clausis.
     *
     * @param where the restriction clause
     * @return the number of rows returned
     * @throws DAOException
     */
    //25
    public int countWhere(String where) throws DAOException
    {
        String sql = "SELECT COUNT(*) AS MCOUNT FROM xref " + where;
        // System.out.println("countWhere: " + sql);
        Connection c = null;
        Statement st = null;
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            c = this.getConnection();
            st = c.createStatement();
            rs =  st.executeQuery(sql);
            if (rs.next())
            {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(st, rs);
            this.freeConnection(c);
            sql = null;
        }
        throw new DataAccessException("Error in countWhere where=[" + where + "]");
    }

    /**
     * Retrieves the number of rows of the table xref with a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return the number of rows returned
     * @throws DAOException
     */
    //26
    private int countByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            int iReturn = -1;
            rs = ps.executeQuery();
            if (rs.next()) {
                iReturn = rs.getInt("MCOUNT");
            }
            if (iReturn != -1) {
                return iReturn;
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
       throw new DataAccessException("Error in countByPreparedStatement");
    }

    /**
     * count the number of elements of a specific XrefBean bean
     *
     * @param bean the XrefBean bean to look for ant count
     * @return the number of rows returned
     * @throws DAOException
     */
    //27
    public int countUsingTemplate(XrefBean bean) throws DAOException
    {
        return this.countUsingTemplate(bean, -1, -1);
    }

    /**
     * count the number of elements of a specific XrefBean bean , given the start row and number of rows.
     *
     * @param bean the XrefBean template to look for and count
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(XrefBean bean, int startRow, int numRows) throws DAOException
    {
        return this.countUsingTemplate(bean, startRow, numRows, SEARCH_EXACT);
    }

    /**
     * count the number of elements of a specific XrefBean bean given the start row and number of rows and the search type
     *
     * @param bean the XrefBean template to look for
     * @param startRow the start row to be used (first row = 1, last row=-1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param searchType exact ?  like ? starting like ?
     * @return the number of rows returned
     * @throws DAOException
     */
    //20
    public int countUsingTemplate(XrefBean bean, int startRow, int numRows, int searchType) throws DAOException
    {
        Connection c = null;
        PreparedStatement ps = null;
        StringBuilder sql = new StringBuilder("SELECT COUNT(*) AS MCOUNT FROM xref");
        StringBuilder sqlWhere = new StringBuilder("");

        try
        {
            if (this.fillWhere(sqlWhere, bean, SEARCH_EXACT) > 0)
            {
                sql.append(" WHERE ").append(sqlWhere);
            }
            else
            {
                // System.out.println("The bean to look is not initialized... counting all...");
            }
            // System.out.println("countUsingTemplate: " + sql.toString());

            c = this.getConnection();
            ps = c.prepareStatement(sql.toString(),
                                    ResultSet.TYPE_SCROLL_INSENSITIVE,
                                    ResultSet.CONCUR_READ_ONLY);
            this.fillPreparedStatement(ps, bean, searchType);

            return this.countByPreparedStatement(ps);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(ps);
            this.freeConnection(c);
            sql = null;
            sqlWhere = null;
        }
    }

    //


    /**
     * fills the given StringBuilder with the sql where clausis constructed using the bean and the search type
     * @param sqlWhere the StringBuilder that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     */
    protected int fillWhere(StringBuilder sqlWhere, XrefBean bean, int searchType)
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        String sqlEqualsOperation = "=";
        if (searchType != SEARCH_EXACT) {
            sqlEqualsOperation = " like ";
        }
        try
        {
            if (bean.isDescriptionModified()) {
                _dirtyCount ++;
                if (bean.getDescription() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("description IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("description ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isProtaccModified()) {
                _dirtyCount ++;
                if (bean.getProtacc() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("protacc IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("protacc ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isRefseqModified()) {
                _dirtyCount ++;
                if (bean.getRefseq() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("refseq IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("refseq ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isGenesymbolModified()) {
                _dirtyCount ++;
                if (bean.getGenesymbol() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("genesymbol IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("genesymbol ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isSpDisplayIdModified()) {
                _dirtyCount ++;
                if (bean.getSpDisplayId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("sp_display_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("sp_display_id ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isSpIdModified()) {
                _dirtyCount ++;
                if (bean.getSpId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("sp_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("sp_id ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isMrnaModified()) {
                _dirtyCount ++;
                if (bean.getMrna() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("mrna IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("mrna ").append(sqlEqualsOperation).append("?");
                }
            }
            if (bean.isKnowngeneRefModified()) {
                _dirtyCount ++;
                if (bean.getKnowngeneRef() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("knowngene_ref IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("knowngene_ref = ?");
                }
            }
            if (bean.isXrefIdModified()) {
                _dirtyCount ++;
                if (bean.getXrefId() == null) {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("xref_id IS NULL");
                } else {
                    sqlWhere.append((sqlWhere.length() == 0) ? " " : " AND ").append("xref_id = ?");
                }
            }
        }
        finally
        {
            sqlEqualsOperation = null;
        }
        return _dirtyCount;
    }

    /**
     * fill the given prepared statement with the bean values and a search type
     * @param ps the PreparedStatement that will be filled
     * @param bean the bean to use for creating the where clausis
     * @param searchType exact ?  like ? starting like ?
     * @return the number of clausis returned
     * @throws DAOException
     */
    protected int fillPreparedStatement(PreparedStatement ps, XrefBean bean, int searchType) throws DAOException
    {
        if (bean == null) {
            return 0;
        }
        int _dirtyCount = 0;
        try
        {
            if (bean.isDescriptionModified()) {
                switch (searchType) {
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getDescription() + "]");
                        if (bean.getDescription() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getDescription()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getDescription() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getDescription() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getDescription());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getDescription() + "]");
                        if (bean.getDescription() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getDescription() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isProtaccModified()) {
                switch (searchType) {
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getProtacc() + "]");
                        if (bean.getProtacc() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getProtacc()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getProtacc() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getProtacc() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getProtacc() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getProtacc());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getProtacc() + "]");
                        if (bean.getProtacc() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getProtacc() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isRefseqModified()) {
                switch (searchType) {
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getRefseq() + "]");
                        if (bean.getRefseq() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getRefseq()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getRefseq() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getRefseq() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getRefseq() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getRefseq());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getRefseq() + "]");
                        if (bean.getRefseq() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getRefseq() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isGenesymbolModified()) {
                switch (searchType) {
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getGenesymbol() + "]");
                        if (bean.getGenesymbol() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getGenesymbol()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getGenesymbol() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getGenesymbol() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getGenesymbol() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getGenesymbol());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getGenesymbol() + "]");
                        if (bean.getGenesymbol() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getGenesymbol() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isSpDisplayIdModified()) {
                switch (searchType) {
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getSpDisplayId() + "]");
                        if (bean.getSpDisplayId() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getSpDisplayId()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getSpDisplayId() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getSpDisplayId() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getSpDisplayId() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getSpDisplayId());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getSpDisplayId() + "]");
                        if (bean.getSpDisplayId() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getSpDisplayId() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isSpIdModified()) {
                switch (searchType) {
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getSpId() + "]");
                        if (bean.getSpId() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getSpId()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getSpId() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getSpId() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getSpId() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getSpId());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getSpId() + "]");
                        if (bean.getSpId() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getSpId() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isMrnaModified()) {
                switch (searchType) {
                    case SEARCH_EXACT:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getMrna() + "]");
                        if (bean.getMrna() == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getMrna()); }
                        break;
                    case SEARCH_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getMrna() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getMrna() + "%");
                        break;
                    case SEARCH_STARTING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [" + bean.getMrna() + "%]");
                        ps.setString(++_dirtyCount, "%" + bean.getMrna());
                        break;
                    case SEARCH_ENDING_LIKE:
                        // System.out.println("Setting for " + _dirtyCount + " [%" + bean.getMrna() + "]");
                        if (bean.getMrna() + "%" == null) { ps.setNull(++_dirtyCount, Types.VARCHAR); } else { ps.setString(++_dirtyCount, bean.getMrna() + "%"); }
                        break;
                    default:
                        throw new DAOException("Unknown search type " + searchType);
                }
            }
            if (bean.isKnowngeneRefModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getKnowngeneRef() + "]");
                if (bean.getKnowngeneRef() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getKnowngeneRef()); }
            }
            if (bean.isXrefIdModified()) {
                // System.out.println("Setting for " + _dirtyCount + " [" + bean.getXrefId() + "]");
                if (bean.getXrefId() == null) { ps.setNull(++_dirtyCount, Types.INTEGER); } else { Manager.setInteger(ps, ++_dirtyCount, bean.getXrefId()); }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        return _dirtyCount;
    }


    //_____________________________________________________________________
    //
    // DECODE RESULT SET
    //_____________________________________________________________________

    /**
     * decode a resultset in an array of XrefBean objects
     *
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the resulting XrefBean table
     * @throws DAOException
     */
    //28
    public XrefBean[] decodeResultSet(ResultSet rs, int[] fieldList, int startRow, int numRows) throws DAOException
    {
    	return (XrefBean[])this.decodeResultSetAsList(rs, fieldList, startRow, numRows).toArray(new XrefBean[0]);
    }

    /**
     * decode a resultset in a list of XrefBean objects
     *
     * @param rs the resultset to decode
     * @param fieldList table of the field's associated constants
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @return the resulting XrefBean table
     * @throws DAOException
     */
    //28
    public List<XrefBean> decodeResultSetAsList(ResultSet rs, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        List<XrefBean> v = new ArrayList<XrefBean>();
        try
        {
            if (rs.absolute(startRow) && numRows!=0)
            {
                int count = 0;
                if(fieldList == null) {
                    do
                    {
                        v.add(decodeRow(rs));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
                else {
                    do
                    {
                        v.add(decodeRow(rs, fieldList));
                        count++;
                    } while ( (count<numRows||numRows<0) && rs.next() );
                }
            }
            return v;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
    }

    /**
     * Transforms a ResultSet iterating on the xref on a XrefBean bean.
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting XrefBean bean
     * @throws DAOException
     */
    //29
    public XrefBean decodeRow(ResultSet rs) throws DAOException
    {
        XrefBean bean = this.createXrefBean();
        try
        {
            bean.setDescription(rs.getString(1));
            bean.setProtacc(rs.getString(2));
            bean.setRefseq(rs.getString(3));
            bean.setGenesymbol(rs.getString(4));
            bean.setSpDisplayId(rs.getString(5));
            bean.setSpId(rs.getString(6));
            bean.setMrna(rs.getString(7));
            bean.setKnowngeneRef(Manager.getInteger(rs, 8));
            bean.setXrefId(Manager.getInteger(rs, 9));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the xref table on a XrefBean bean according to a list of fields.
     *
     * @param rs the ResultSet to be transformed
     * @param fieldList table of the field's associated constants
     * @return bean resulting XrefBean bean
     * @throws DAOException
     */
    //30
    public XrefBean decodeRow(ResultSet rs, int[] fieldList) throws DAOException
    {
        XrefBean bean = this.createXrefBean();
        int pos = 0;
        try
        {
            for(int i = 0; i < fieldList.length; i++)
            {
                switch(fieldList[i])
                {
                    case ID_DESCRIPTION:
                        ++pos;
                        bean.setDescription(rs.getString(pos));
                        break;
                    case ID_PROTACC:
                        ++pos;
                        bean.setProtacc(rs.getString(pos));
                        break;
                    case ID_REFSEQ:
                        ++pos;
                        bean.setRefseq(rs.getString(pos));
                        break;
                    case ID_GENESYMBOL:
                        ++pos;
                        bean.setGenesymbol(rs.getString(pos));
                        break;
                    case ID_SP_DISPLAY_ID:
                        ++pos;
                        bean.setSpDisplayId(rs.getString(pos));
                        break;
                    case ID_SP_ID:
                        ++pos;
                        bean.setSpId(rs.getString(pos));
                        break;
                    case ID_MRNA:
                        ++pos;
                        bean.setMrna(rs.getString(pos));
                        break;
                    case ID_KNOWNGENE_REF:
                        ++pos;
                        bean.setKnowngeneRef(Manager.getInteger(rs, pos));
                        break;
                    case ID_XREF_ID:
                        ++pos;
                        bean.setXrefId(Manager.getInteger(rs, pos));
                        break;
                    default:
                        throw new DAOException("Unknown field id " + fieldList[i]);
                }
            }
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    /**
     * Transforms a ResultSet iterating on the xref on a XrefBean bean using the names of the columns
     *
     * @param rs the ResultSet to be transformed
     * @return bean resulting XrefBean bean
     * @throws DAOException
     */
    //31
    public XrefBean metaDataDecodeRow(ResultSet rs) throws DAOException
    {
        XrefBean bean = this.createXrefBean();
        try
        {
            bean.setDescription(rs.getString("description"));
            bean.setProtacc(rs.getString("protacc"));
            bean.setRefseq(rs.getString("refseq"));
            bean.setGenesymbol(rs.getString("genesymbol"));
            bean.setSpDisplayId(rs.getString("sp_display_id"));
            bean.setSpId(rs.getString("sp_id"));
            bean.setMrna(rs.getString("mrna"));
            bean.setKnowngeneRef(Manager.getInteger(rs, "knowngene_ref"));
            bean.setXrefId(Manager.getInteger(rs, "xref_id"));
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }

        bean.isNew(false);
        bean.resetIsModified();

        return bean;
    }

    //////////////////////////////////////
    // PREPARED STATEMENT LOADER
    //////////////////////////////////////

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of XrefBean
     * @throws DAOException
     */
    //32
    public XrefBean[] loadByPreparedStatement(PreparedStatement ps) throws DAOException
    {
        return this.loadByPreparedStatement(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement.
     *
     * @param ps the PreparedStatement to be used
     * @return an array of XrefBean
     * @throws DAOException
     */
    //32
    public List<XrefBean> loadByPreparedStatementAsList(PreparedStatement ps) throws DAOException
    {
        return this.loadByPreparedStatementAsList(ps, null);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of XrefBean
     * @throws DAOException
     */
    //33
    public XrefBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList) throws DAOException
    {
        return (XrefBean[])this.loadByPreparedStatementAsList(ps, fieldList).toArray(new XrefBean[0]);
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved.
     *
     * @param ps the PreparedStatement to be used
     * @param fieldList table of the field's associated constants
     * @return an array of XrefBean
     * @throws DAOException
     */
    //33
    public List<XrefBean> loadByPreparedStatementAsList(PreparedStatement ps, int[] fieldList) throws DAOException
    {		        
        ResultSet rs =  null;
		List<XrefBean> v =  null;
        try
        {
            rs =  ps.executeQuery();
            v = new ArrayList<XrefBean>();
			if(fieldList == null) {
				while(rs.next()) {
					v.add(decodeRow(rs));
				}
			}
			else {
				while(rs.next()) {
					v.add(decodeRow(rs, fieldList));
				}
			}

			return v;
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            getManager().close(rs);
        }
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of XrefBean
     * @throws DAOException
     */
    //34
    public XrefBean[] loadByPreparedStatement(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            rs = ps.executeQuery();
            return this.decodeResultSet(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
    }

    /**
     * Loads all the elements using a prepared statement specifying a list of fields to be retrieved,
     * and specifying the start row and the number of rows.
     *
     * @param ps the PreparedStatement to be used
     * @param startRow the start row to be used (first row = 1, last row = -1)
     * @param numRows the number of rows to be retrieved (all rows = a negative number)
     * @param fieldList table of the field's associated constants
     * @return an array of XrefBean
     * @throws DAOException
     */
    //34
    public List<XrefBean> loadByPreparedStatementAsList(PreparedStatement ps, int[] fieldList, int startRow, int numRows) throws DAOException
    {
        ResultSet rs =  null;
        try
        {
            rs = ps.executeQuery();
            return this.decodeResultSetAsList(rs, fieldList, startRow, numRows);
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
        finally
        {
            this.getManager().close(rs);
        }
    }

    //_____________________________________________________________________
    //
    // LISTENER
    //_____________________________________________________________________
    private XrefListener listener = null;

    /**
     * Registers a unique XrefListener listener.
     */
    //35
    public void registerListener(XrefListener listener)
    {
        this.listener = listener;
    }

    /**
     * Before the save of the XrefBean bean.
     *
     * @param bean the XrefBean bean to be saved
     */
    //36
    private void beforeInsert(XrefBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeInsert(bean);
        }
    }

    /**
     * After the save of the XrefBean bean.
     *
     * @param bean the XrefBean bean to be saved
     */
    //37
    private void afterInsert(XrefBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterInsert(bean);
        }
    }

    /**
     * Before the update of the XrefBean bean.
     *
     * @param bean the XrefBean bean to be updated
     */
    //38
    private void beforeUpdate(XrefBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeUpdate(bean);
        }
    }

    /**
     * After the update of the XrefBean bean.
     *
     * @param bean the XrefBean bean to be updated
     */
    //39
    private void afterUpdate(XrefBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterUpdate(bean);
        }
    }

    /**
     * Before the delete of the XrefBean bean.
     *
     * @param bean the XrefBean bean to be deleted
     */
    private void beforeDelete(XrefBean bean) throws DAOException
    {
        if (listener != null) {
            listener.beforeDelete(bean);
        }
    }

    /**
     * After the delete of the XrefBean bean.
     *
     * @param bean the XrefBean bean to be deleted
     */
    private void afterDelete(XrefBean bean) throws DAOException
    {
        if (listener != null) {
            listener.afterDelete(bean);
        }
    }

    //_____________________________________________________________________
    //
    // UTILS
    //_____________________________________________________________________

    /**
     * Retrieves the manager object used to get connections.
     *
     * @return the manager used
     */
    //40
    private Manager getManager()
    {
        return Manager.getInstance();
    }

    /**
     * Frees the connection.
     *
     * @param c the connection to release
     */
    //41
    private void freeConnection(Connection c)
    {
        this.getManager().releaseConnection(c); // back to pool
    }

    /**
     * Gets the connection.
     */
    //42
    private Connection getConnection() throws DAOException
    {
        try
        {
            return this.getManager().getConnection();
        }
        catch(SQLException e)
        {
            throw new DataAccessException(e);
        }
    }
}
